[common.consensus_config]
first_round_timeout = 3000
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 4

[common.services_config]

[node]
address = "127.0.0.1:6332"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "4d711312fc29e87eed752d75b160f0d12aee4506b0efa0d3461de1988d6e654e"
service_key = "e48a4f3c6e6c706cba2d4245dfe715d48c36c63a355ee8026e272be2ad6b6007"
