[common.consensus_config]
first_round_timeout = 3000
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 4

[common.services_config]

[node]
address = "127.0.0.1:6331"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "c3929aad3affebc8402c64f99e83d584fef13318142a5501f12ea51eb185ec04"
service_key = "749d2d41913b5599b5ae161593c0e93253c1a8566b38eb418d2cd74daa8d60ed"
